name: mobile_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  api_service:
    path: ./api_service
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  equatable: ^2.0.5
  get_it: ^8.0.3
  dio: ^5.8.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  